---
title: "IX/XI/XX Models"
output: html_notebook
---

# Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse",
                     "sf")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector) {
  library(package, character.only = TRUE)
}

```

# Remote I/O
```{r remote-io}
private_dir <- "../../docs/data/_PRIVATE/"
data_dir <- "../../docs/data/input/"

clean_ie_streetlight_filename <- paste0(private_dir, "clean-streetlight.rds")
clean_ee_streetlight_filename <- paste0(private_dir, "clean-itre-streetlight.rds")
socec_filename <- paste0(data_dir, "ieei/se_2016.csv")
taz_shape_filename <- paste0(data_dir, "tazs/master_tazs.shp")
ext_nodes_shape_filename <- paste0(data_dir, "ieei/ext_nodes.shp")

campo_sl_shape <- paste0(private_dir, "streetlight/161428_TRM20test5_2016/Shapefile/161428_TRM20test5_2016_origin/161428_TRM20test5_2016_origin.shp")
durham_sl_shape <- paste0(private_dir, "streetlight/164792_TRM20_2016_All/Shapefile/164792_TRM20_2016_All_origin/164792_TRM20_2016_All_origin.shp")

output_filename <- paste0(data_dir, "ieei/estimated-flows.csv")
```

# Parameters
```{r parameters}
LAT_LNG_EPSG <- 4326
```

# Data Reads
```{r read}
sl_ie_df <- readRDS(clean_ie_streetlight_filename)
sl_ee_df <- readRDS(clean_ee_streetlight_filename)

socec_df <- read_csv(socec_filename, col_types = cols(.default = col_double(),
                                                      TAZ = col_integer(),
                                                      Type = col_character()))

taz_sf <- st_read(taz_shape_filename) %>%
  st_transform(LAT_LNG_EPSG)

ext_nodes_sf <- st_read(ext_nodes_shape_filename) %>%
  st_transform(LAT_LNG_EPSG)

campo_sf <- st_read(campo_sl_shape, crs = LAT_LNG_EPSG)
durham_sf <- st_read(durham_sl_shape, crs = LAT_LNG_EPSG)
```

# Get Coordinates for Master Zones
```{r get-coords}
centroids_sf <- select(taz_sf, taz = ID, geometry) %>%
  st_centroid()

centroids_df <- as_tibble(st_coordinates(centroids_sf)) %>%
  bind_cols(., tibble(taz = centroids_sf$taz)) %>%
  rename(lat = Y, lng = X)

```

# Get Coordinates for StreetLight TAZs
```{r}
c_sf <- campo_sf %>%
  filter(is_pass == 0) %>%
  select(id, geometry) %>%
  st_centroid(.)

d_sf <- durham_sf %>%
  filter(is_pass == 0) %>%
  select(id, geometry) %>%
  st_centroid(.)

sl_centroids_df <- bind_rows(
  mutate(
    bind_cols(as_tibble(st_coordinates(c_sf)),
              tibble(zone = c_sf$id)),
    source = "campo"),
  mutate(
    bind_cols(as_tibble(st_coordinates(d_sf)),
              tibble(zone = d_sf$id)),
    source = "durham")) %>%
  mutate(zone = as.integer(zone)) %>%
  rename(lat = Y, lng = X)

remove(c_sf, d_sf)
```

# Find Closest Master TAZ to StreetLight TAZ
```{r closest}
internal_taz_vector <- socec_df %>%
  filter(Type == "Internal") %>%
  .$TAZ

working_df <- centroids_df %>%
  select(master_taz = taz, master_lat = lat, master_lng = lng) %>%
  full_join(., sl_centroids_df, by = character()) %>%
  mutate(distance = sqrt((master_lat - lat)**2 + (master_lng - lng)**2))

closest_df <- working_df %>%
  group_by(zone, source) %>%
  summarise(min_dist = min(distance), .groups = "drop") %>%
  left_join(working_df, ., by = c("zone", "source")) %>%
  filter(distance <= min_dist) %>%
  select(taz = master_taz,
         sl_zone = zone,
         sl_source = source) %>%
  mutate(taz = as.integer(taz)) %>%
  filter(taz %in% internal_taz_vector) 
```

# Match External Stations
```{r external-stations}
external_centroids_df <- as_tibble(st_coordinates(ext_nodes_sf)) %>%
  bind_cols(tibble(taz = ext_nodes_sf$ID)) %>%
  rename(lat = Y, lng = X)

working_df <- external_centroids_df %>%
  select(master_taz = taz, master_lat = lat, master_lng = lng) %>%
  full_join(., sl_centroids_df, by = character()) %>%
  mutate(distance = sqrt((master_lat - lat)**2 + (master_lng - lng)**2))

closest_ext_df <- working_df %>%
  group_by(zone, source) %>%
  summarise(min_dist = min(distance), .groups = "drop") %>%
  left_join(working_df, ., by = c("zone", "source")) %>%
  filter(distance <= min_dist) %>%
  select(taz = master_taz,
         sl_zone = zone,
         sl_source = source) %>%
  mutate(taz = as.integer(taz))
```


# IE-Reductions
```{r reductions}
working_ie_df <- sl_ie_df %>%
  filter(type == "Personal") %>%
  filter(day_type == "1: Weekday (M-Th)") %>%
  filter(flow > 0) %>%
  filter(orig_pass_through == "yes" | dest_pass_through == "yes") %>%
  filter(orig_zone != dest_zone) %>%
  mutate(purpose = "Missing") %>%
  mutate(purpose = if_else(orig_pass_through == "yes" & dest_pass_through == "yes", "XX", purpose)) %>%
  mutate(purpose = if_else(orig_pass_through == "yes" & dest_pass_through == "no", "IX", purpose)) %>%
  mutate(purpose = if_else(orig_pass_through == "no" & dest_pass_through == "yes", "XI", purpose)) %>%
  left_join(., closest_df, by = c("orig_zone" = "sl_zone", "source" = "sl_source")) %>%
  mutate(orig_taz = if_else(purpose == "IX", taz, as.integer(NA))) %>%
  select(-taz) %>%
  left_join(., closest_df, by = c("dest_zone" = "sl_zone", "source" = "sl_source")) %>%
  mutate(dest_taz = if_else(purpose == "XI", taz, as.integer(NA))) %>%
  select(-taz) %>%
  left_join(., closest_ext_df, by = c("orig_zone" = "sl_zone", "source" = "sl_source")) %>%
  mutate(orig_taz = if_else(purpose %in% c("XX", "XI"), taz, orig_taz)) %>%
  select(-taz) %>%
  left_join(., closest_ext_df, by = c("dest_zone" = "sl_zone", "source" = "sl_source")) %>%
  mutate(dest_taz = if_else(purpose %in% c("XX", "IX"), taz, dest_taz)) %>%
  select(-taz) %>%
  left_join(., centroids_df, by = c("orig_taz" = "taz")) %>%
  mutate(orig_lat = if_else(purpose == "IX", lat, as.double(NA))) %>%
  mutate(orig_lng = if_else(purpose == "IX", lng, as.double(NA))) %>%
  select(-lat, -lng) %>%
  left_join(., centroids_df, by = c("dest_taz" = "taz")) %>%
  mutate(dest_lat = if_else(purpose == "XI", lat, as.double(NA))) %>%
  mutate(dest_lng = if_else(purpose == "XI", lng, as.double(NA))) %>%
  select(-lat, -lng) %>%
  left_join(., external_centroids_df, by = c("orig_taz" = "taz")) %>%
  mutate(orig_lat = if_else(purpose %in% c("XI", "XX"), lat, orig_lat)) %>%
  mutate(orig_lng = if_else(purpose %in% c("XI", "XX"), lng, orig_lng)) %>%
  select(-lat, -lng) %>%
  left_join(., external_centroids_df, by = c("dest_taz" = "taz")) %>%
  mutate(dest_lat = if_else(purpose %in% c("IX", "XX"), lat, dest_lat)) %>%
  mutate(dest_lng = if_else(purpose %in% c("IX", "XX"), lng, dest_lng)) %>%
  select(-lat, -lng)

```

# Combine IE with EE
```{r combine}
working_df <- working_ie_df %>%
  filter(day_part == "0: All Day (12am-12am)") %>%
  select(-orig_zone, -dest_zone, -orig_lat, -orig_lng, -dest_lat, -dest_lng) %>%
  filter(!is.na(orig_taz)) %>%
  filter(!is.na(dest_taz)) %>%
  filter(purpose %in% c("IX", "XI"))

bind_ee_df <- sl_ee_df %>%
  mutate(source = "itre") %>%
  mutate(purpose = "XX")

combined_df <- bind_rows(working_df, bind_ee_df)

```

# Make Seed
```{r seed}
seed_df <- expand_grid(orig_taz = socec_df$TAZ, dest_taz = socec_df$TAZ) %>%
  mutate(orig_internal = orig_taz %in% internal_taz_vector) %>%
  mutate(dest_internal = dest_taz %in% internal_taz_vector) %>%
  filter(!(orig_internal & dest_internal)) %>%
  mutate(ext_station = if_else(orig_internal, dest_taz, orig_taz)) %>%
  mutate(purpose = "XX") %>%
  mutate(purpose = if_else(orig_internal, "IX", purpose)) %>%
  mutate(purpose = if_else(dest_internal, "XI", purpose)) %>%
  filter(orig_taz != dest_taz) %>%
  left_join(., select(combined_df, -purpose), by = c("orig_taz", "dest_taz")) %>%
  mutate(seed = if_else(is.na(flow), 1.0, flow))
```

# Make Output
```{r output}
adjust_df <- seed_df %>%
  group_by(ext_station) %>%
  summarise(volume = sum(seed), .groups = "drop") %>%
  left_join(., select(socec_df, ext_station = TAZ, ADT), by = c("ext_station")) %>%
  mutate(adjust = ADT / volume) %>%
  select(ext_station, adjust)
  
output_df <- left_join(seed_df, adjust_df, by = c("ext_station")) %>%
  mutate(flow_estimate = seed * adjust) %>%
  left_join(., select(socec_df, ext_station = TAZ, PCTAUTOEE, ADT), by = c("ext_station")) %>%
  left_join(., centroids_df, by = c("orig_taz" = "taz")) %>%
  mutate(orig_lat = if_else(purpose == "IX", lat, as.double(NA))) %>%
  mutate(orig_lng = if_else(purpose == "IX", lng, as.double(NA))) %>%
  select(-lat, -lng) %>%
  left_join(., centroids_df, by = c("dest_taz" = "taz")) %>%
  mutate(dest_lat = if_else(purpose == "XI", lat, as.double(NA))) %>%
  mutate(dest_lng = if_else(purpose == "XI", lng, as.double(NA))) %>%
  select(-lat, -lng) %>%
  left_join(., external_centroids_df, by = c("orig_taz" = "taz")) %>%
  mutate(orig_lat = if_else(purpose %in% c("XI", "XX"), lat, orig_lat)) %>%
  mutate(orig_lng = if_else(purpose %in% c("XI", "XX"), lng, orig_lng)) %>%
  select(-lat, -lng) %>%
  left_join(., external_centroids_df, by = c("dest_taz" = "taz")) %>%
  mutate(dest_lat = if_else(purpose %in% c("IX", "XX"), lat, dest_lat)) %>%
  mutate(dest_lng = if_else(purpose %in% c("IX", "XX"), lng, dest_lng)) %>%
  select(-lat, -lng)
```



# Write
```{r write}
write_csv(output_df, output_filename)
```

