---
title: "Acronyms"
author: "Caliper Corporation"
date: "February 8, 2021"
output: 
  html_document:
    toc: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The page simply defines a number of common acronyms used throughout the
documentation.

- TRMG2: Triangle Regional Model Generation 2
- ITRE: Insitute for Transportation Research and Education
- RTP: Research Triangle Park
- ACS: American Community Survey
- NHTS: National Household Travel Survey
- TAZ: Traffic Analysis Zone
- SOV: Single-occupancy vehicle
- HOV: High-occupancy vehicle
- IPF: Iterative Proportional Fitting
- IPU: Iterative Proportional Updating
- HH: Household
- HB: Home-based
- NHB: Non-home-based

## Trip Types
Trip types have the following form: "N_HB_OD_Short"

Each of the four pieces of this classification convey information about the trip.

- Tour Type
  - W: Work
  - N: Non-work
- Home-based
  - HB: Home-based
  - NHB: Non-home-based
- Trip Purpose
  - Various. See [here](resident_production.html)
- Activity Duration
  - Short
  - Long
  - All